### ISSUE TITLE
Various issues with lint target

### ISSUE THREAD

**Issue by Den-dp** [spartan-ng/spartan#362]
### Please provide the environment you discovered this bug in.

I was unable to run `npx nx run-many -t lint --all` on Windows

### Which area/package is the issue in?

Don't know / other

### Description

I found 3 issues with it:

1. The current `@nx/eslint` package version doesn't work on Windows (cause it duplicates a path), so it requires at least `nx migrate 19.3.2` where it is fixed https://github.com/nrwl/nx/pull/26687
```
> npx nx lint cli

> nx run cli:lint

Linting "cli"...
 NX   ENOENT: no such file or directory, stat 'C:\Users\denis\github\C:\Users\denis\github\spartan\libs\cli\eslint.config.js'
```
2. after `nx migrate 19.3.2`, I found another issue related to the recent `eslint.config.cjs` rename without renaming all usages, like
https://github.com/goetzrobin/spartan/blob/30bf1fa0159b9534823db66cdc65a756b38089cc/libs/cli/eslint.config.js#L2 
```
> npx nx lint cli

> nx run cli:lint

Linting "cli"...
 NX   Cannot find module '../../eslint.config.js'
Require stack:
- C:\Users\denis\github\spartan\libs\cli\eslint.config.js
```
3. after changing all `eslint.config.js` references to `eslint.config.cjs`, I found that there are some packages with lint errors
```
> nx run ui-forms-brain:lint


Linting "ui-forms-brain"...

C:\Users\denis\github\spartan\libs\ui\forms\brain\package.json
  4:3  error  The "ui-forms-brain" project uses the following packages, but they are missing from "peerDependencies":
    - @angular/forms  @nx/dependency-checks
  6:5  error  The "@spartan-ng/ui-core" package is not used by "ui-forms-brain" project                                                     @nx/dependency-checks
  7:5  error  The "class-variance-authority" package is not used by "ui-forms-brain" project                                                @nx/dependency-checks
  8:5  error  The "clsx" package is not used by "ui-forms-brain" project                                                                    @nx/dependency-checks

...

 NX   Running target lint for 66 projects failed

Failed tasks:

- ui-icon-helm:lint
- ui-tooltip-brain:lint
- ui-forms-brain:lint
- ui-form-field-brain:lint
- ui-select-brain:lint
- ui-tooltip-helm:lint
- ui-input-helm:lint
- ui-form-field-helm:lint
- ui-select-helm:lint
- ui-tabs-helm:lint
- @spartan-ng/ui-slider-brain:lint
- app:lint
- ui-storybook-e2e:lint
- trpc:lint
- trpc-app-e2e:lint
- @spartan-ng/ui-slider-helm:lint
- cli:lint
- tools:lint
```

4. and also found that there are packages that still use `.eslintrc.json` which is missing
```
> nx run ui-tooltip-brain:lint

Linting "ui-tooltip-brain"...
 NX   Failed to load config "../../../../.eslintrc.json" to extend from.
Referenced from: C:\Users\denis\github\spartan\libs\ui\tooltip\brain\.eslintrc.json
```

### Other information

Overall, [the decision to migrate to esm](https://github.com/goetzrobin/spartan/blob/30bf1fa0159b9534823db66cdc65a756b38089cc/package.json#L5) in the NX workspace complicates things a lot:
- requires many renames
- requires reconfigurations in nx.json https://github.com/goetzrobin/spartan/blob/30bf1fa0159b9534823db66cdc65a756b38089cc/nx.json#L21
- requires dealing with all NX generators configured to work with JS and not CJS

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
@Den-dp thanks for pointing this out. I think the goal is to actually move from eslint to biome. That definitely needs some cleaning up and love though. Thanks for putting this list together! Are you able to run `pnpm exec biome.lint` at the root?

**Comment by goetzrobin** [comment]
@benpsnyder I think this is related to what we were talking about on Discord, correct? Feel free to assign yourself if that's correct!

**Comment by benpsnyder** [comment]
I'll take this on and update this issue. I have self-assigned.

**Comment by benpsnyder** [comment]
@goetzrobin I added you as a reviewer/approver on this #392 ... I think we should complete this first as it addresses ping 1,2,4 on this thread.

Then we can address point 3 in other PRs because that involves more than config change.
