### ISSUE TITLE
Netlify deployment analog/trpc routes functions failed

### ISSUE THREAD

**Issue by louiiuol** [spartan-ng/spartan#403]
### Please provide the environment you discovered this bug in.

Analog 1.7.2
Nx 19.8.3
Netlify 

### Which area/package is the issue in?

trpc

### Description

I have a NX monorepo which contains an analog app serving as a SPA and also provides trpc routes. Locally, everything works fine, but the problem starts when i try to deploy it on Netlify, api routes are not availables. I've tried adding `_redirects` file inside `public/` folder: 

```md
/api/* /.netlify/functions/server 200
/*    /index.html   200
```

But routes keep return its either:
- unexpected end of JSON input
- returning 404
- unexpected lambda errors.. 

In order to debug this mess, I've launched locally deployment with `netlify dev` command:
SPA works just fine with routing as expected, but when i get to http://../api/v1/hello (i've kept default example from analog generator) my server returns the following error: 

```md
◈ Injecting environment variable values for all scopes
◈ Ignored general context env var: DEPLOY_PRIME_URL (defined in .env file)
◈ Injected .env file env var: DEPLOY_PRIME_URL
◈ Ignored general context env var: LANG (defined in process)
◈ Injected .env file env var: DATABASE_URL
◈ No app server detected. Using simple static server
◈ Running static server from "../dist/apps/app-name/analog/public"
◈ Setting up local development server
Cleaned up apps/app-name/.netlify/functions-internal.

◈ Static server listening to 3999

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

◈ Loaded function server

◈ Rewrote URL to /.netlify/functions/server
Request from ::1: GET /.netlify/functions/server
[nitro] [uncaughtException] {
  errorMessage: 'e.default is not a function',
  errorType: 'TypeError',
  stackTrace: [
    'file:///.../.netlify/functions-serve/server/___netlify-bootstrap.mjs:2:26751',
    'AsyncLocalStorage.run (node:async_hooks:338:14)',
    'file:///.../.netlify/functions-serve/server/___netlify-bootstrap.mjs:2:26690',
    'Object.<anonymous> (/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:88:46)',
    'step (/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:67:23)',
    'Object.next (/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:48:53)',
    '/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:42:71',
    'new Promise (<anonymous>)',
    '__awaiter (/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:38:12)',
    '/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:78:64'
  ]
}
Listening on http://[::]:3000
```

Some things makes me curious like this `◈ No app server detected. Using simple static server` 
Is that normal ? Shouldn't it create a server ? 
Also, after init, we can see `Loaded function server` but shouldn't it list my functions (ex: hello) ? 

I wonder if the problem is located in vite/nitro config ? (after seeing stacktrace) or typescript configuration, but everything works locally .. 

Many thanks for your help 🙏

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by thatsamsonkid** [comment]
@louiiuol - This type of issue might be better suited to be raised in https://github.com/analogjs/analog repo instead. Closing since this doesnt seem to be spartan UI related
