### ISSUE TITLE
Calendar - Header is not updating on mobile

### ISSUE THREAD

**Issue by mayerzx** [spartan-ng/spartan#489]
### Please provide the environment you discovered this bug in.

I saw it in the spartan.ng components calendar page.

### Which area/package is the issue in?

calendar

### Description

On mobile when I pick a date then switch the current month, the header doesn't update to the new month/year.

I can't reproduce this issue on desktop, so might be a webkit related issue.

A screenshot where the selected date is in January and after move we see the current month has 28 days but still shown January:
![250112bb-ffc5-4260-9e3b-3d4992b2b2d8](https://github.com/user-attachments/assets/dfaad916-c87e-4235-90b3-a0e47e9416f2)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
Unfortunately I was not able to reproduce this on my phone...

https://github.com/user-attachments/assets/714144c6-5a07-4c19-bb60-3c7ca0f798a2

**Comment by mayerzx** [comment]
I rechecked it. It seems it happens after i tap on the header parts:

https://github.com/user-attachments/assets/4fa0264e-fae1-4688-aaf4-42e954c83230

**Comment by ashley-hunter** [comment]
I believe this is a Edge browser bug. If you turn off the copilot feature in the browser settings the issue no longer occurs, so Copilot seems to be doing something weird causing things to break.
