### ISSUE TITLE
Update ngx-scrollbar to the latest version

### ISSUE THREAD

**Issue by hillin** [spartan-ng/spartan#510]
### Which scope/s are relevant/related to the feature request?

scroll-area

### Information

The scroll area component uses a rather old version of ngx-scrollbar. As we are also using the latest version of the lib elsewhere in our project, we can't get them to coexist. It would be lovely to use the latest ngx-scrollbar in spartan.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by goetzrobin** [comment]
Seems like this is a good idea as it also addresses the issue in #521
