### ISSUE TITLE
@spartan-ng/cli :ui Generates 2 src

### ISSUE THREAD

**Issue by Applicafroguy** [spartan-ng/spartan#515]
### Please provide the environment you discovered this bug in.

OS: ArcoLinux x86_64 

Angular 19.0.0
NX Workspace 20.2.1

### Which area/package is the issue in?

Don't know / other

### Description

When I install a component ```npx nx g @spartan-ng/cli:ui alert``` it generates 2 src folders, I have to manually copy src.  This is a new project. 

![spartan](https://github.com/user-attachments/assets/373fdb9b-47c0-4a48-8371-1af53e27d4ce)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
This should be fixed by #516. It's already merged so I will test it and release a new CLI version!

**Comment by goetzrobin** [comment]
just released a fix for this in 0.0.1-alpha.373
