### ISSUE TITLE
scroll-area is not working in Firefox

### ISSUE THREAD

**Issue by ajitzero** [spartan-ng/spartan#521]
### Please provide the environment you discovered this bug in.

https://www.spartan.ng/components/scroll-area

Firefox: 134.0b7 (64-bit) on Windows

### Which area/package is the issue in?

scroll-area

### Description

Current behaviour: Scroll bar is not present in scroll-area, when using Firefox. Unable to scroll with mouse wheel (so not just a visual bug).

Works in Chrome.

See:
- The main example at: https://www.spartan.ng/components/scroll-area
- The docs left menu.

### Other information

It appears to be an issue with the polyfill. It could be related to https://github.com/MurhafSousli/ngx-scrollbar/issues/674 or https://github.com/MurhafSousli/ngx-scrollbar/issues/615, but it doesn't explain why our current pinned versions broke.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
@ajitzero we should probably update to the newest version that includes the fix he describes? have you tried this to see if that resolves the issue?

**Comment by ajitzero** [comment]
I'll try to upgrade and check this weekend! Completely swamped with work 😅

**Comment by ashley-hunter** [comment]
May be resolved by #529, but it works for me in Firefox on Mac (even in the current docs), so I can't verify one way or another

**Comment by ajitzero** [comment]
I verified on Firefox on Windows, and this is working now! Thank you @ashley-hunter

**Comment by ashley-hunter** [comment]
Brilliant! Thank you for verifying!
